version: '2'
services:
    trucks-app:
        image: trucks
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trucks-mysql:3306/trucks?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trucks-mysql:
        extends:
            file: mysql.yml
            service: trucks-mysql
